- designs.json
> Spalsh screen

- designs.json
Issue: 4
Added an icon.
Added an icon.
-
-
-
> Icon added

- app/src/main/res/values/contributor.xml
Issue: 31
Added my name as a contributor for future purposes.
> contributer?

- app/src/main/res/values/contributor.xml
> updated constructors.xml

- app/src/main/res/values/contributor.xml
> contributor

- app/src/main/res/values/contributor.xml
> Added data in contributors.xml

- app/src/main/java/com/example/superquizzer/RegisterActivity.kt
- app/src/main/res/layout/activity_register.xml
Issue: 18
Add Register User Function in RegisterActivity.kt
- changes some button id and auto fill
-
https://user-images.githubusercontent.com/96480565/209149578-bb06efeb-2d15-4884-84df-ef0031295614.mp4
-
> user commit

- app/src/main/res/values/contributor.xml
> added pragya1976 in comtibutors

- app/src/main/res/values/contributor.xml
Issue: 31
- Added Name-contributor.xml
> Added Name

- app/src/main/res/values/contributor.xml
> issue_31_contributor_details

- app/build.gradle
- app/src/main/java/com/example/superquizzer/RegisterActivity.kt
Issue: 54
I add firebase auth in register activity.
-added user with email and password in firebase console
https://user-images.githubusercontent.com/96480565/209437624-3253b172-5072-4bf3-abf4-7a62b76e3fe6.mp4
-
-
> fire commit

- app/src/main/java/com/example/superquizzer/ForgotPasswordActivity.kt
- app/src/main/res/drawable/ic_baseline_arrow_white_back_24.xml
- app/src/main/res/layout/activity_forgot_password.xml
Issue: 67
Add a back button 
add validate eamil func in forgotpassword activity
-add a back button
https://user-images.githubusercontent.com/96480565/209642512-1d544a87-5511-4ae0-b1bd-4f194b897ac6.mp4
-
-
> change commit

- app/src/main/java/com/example/superquizzer/Question.kt
Issue: 73
Add data class
-Add variable to data class
-
-
> Classbranch

- app/src/main/java/com/example/superquizzer/Question.kt
Issue: 73
Add data class
-add variables in the data classes
-
-
> data commit

- app/src/main/res/values/contributor.xml
Issue: 31
Added my name in contributor.xml
changes made in contributor.xml file
-
-
-
> name added as contributor

- app/src/main/res/values/contributor.xml
Issue: 31
Short description of what this resolves:
Added my name in contributor.xml
> added my name in contributor.xml

- app/src/main/java/com/example/superquizzer/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
Issue: 78
Add logout feature 
Add firebase auth
-Add dialog box
-
-
> tool commit

- README.md
Issue: 83
added contributors section
> Top contributors

- app/src/main/res/values/contributor.xml
> updated contributor.xml

- app/src/main/java/com/example/superquizzer/ForgotPasswordActivity.kt
Issue: 76
add reset password feature
-email sent  for reset password to the registered email
-
-
> reset commit

- app/src/main/res/values/contributor.xml
> Added name in contributors.xml

- app/src/main/res/values/contributor.xml
Issue: 31
Added my name in contributor.xml
Added my name in contributor.xml
-
-
-
> Added name in the contributor.xml

- app/src/main/java/com/example/superquizzer/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
Issue: 96
Here I add share button for text.
-add share button in main activity
-
-
> share commit

- app/src/main/java/com/example/superquizzer/MainActivity.kt
- app/src/main/java/com/example/superquizzer/ScienceActivity.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_science.xml
- app/src/main/res/layout/dialog_progress.xml
Issue: 95
Added the functionality of the science activity
Added the functionality of the science activity
-
-
-
> science activity

- app/src/main/java/com/example/superquizzer/AnimeQuestions.kt
- app/src/main/java/com/example/superquizzer/GKQuestions.kt
- app/src/main/java/com/example/superquizzer/GamingQuestions.kt
- app/src/main/java/com/example/superquizzer/MusicQuestions.kt
- app/src/main/java/com/example/superquizzer/SportsQuestion.kt
Issue: 98
Add Questions and ans 
-Add qusetions and ans 
-
-
> ans commit

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/superquizzer/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
Issue: 101
fixes bug
-changes in activitymain.xml
-
-
> bug commit

- app/src/main/java/com/example/superquizzer/MainActivity.kt
- app/src/main/java/com/example/superquizzer/Settings.kt
- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/values/themes.xml
Issue: 107
added settings activity
-
-
-
> settings added

- app/src/main/java/com/example/superquizzer/AnimeActivity.kt
- app/src/main/java/com/example/superquizzer/GKActivity.kt
- app/src/main/java/com/example/superquizzer/GamingActivity.kt
- app/src/main/java/com/example/superquizzer/MainActivity.kt
- app/src/main/java/com/example/superquizzer/MusicActivity.kt
- app/src/main/java/com/example/superquizzer/ScienceActivity.kt
- app/src/main/java/com/example/superquizzer/Settings.kt
- app/src/main/java/com/example/superquizzer/SportsActivity.kt
- app/src/main/res/anim/enter_activity.xml
- app/src/main/res/anim/exit_activity.xml
- app/src/main/res/values/themes.xml
https://user-images.githubusercontent.com/96480565/212123103-9c78f0e9-b34b-443a-85e8-dcec264c6f79.mp4
Issue: 118
animation added
-anim added
- after logout the screen come to log in page
-
> anim added

- README.md
> google drive link added before getting started
